<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerWBNxxxb\srcDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerWBNxxxb/srcDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerWBNxxxb.legacy');

    return;
}

if (!\class_exists(srcDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerWBNxxxb\srcDevDebugProjectContainer::class, srcDevDebugProjectContainer::class, false);
}

return new \ContainerWBNxxxb\srcDevDebugProjectContainer(array(
    'container.build_hash' => 'WBNxxxb',
    'container.build_id' => '9f8e5535',
    'container.build_time' => 1526481679,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerWBNxxxb');
